### PR TITLE
Change var to const/let

### PR DESCRIPTION
**Pull request by perception30**

### CODE REVIEW

**Comment by bsoyka** [comment]
https://github.com/kleampa/not-paid/blob/ddfd07e118e0b642676b0180a0b71daf7357eea1/README.md#L26
#10

**Comment by imlinus** [comment]
Sorry, the meme has died 😿

**Comment by brhx** [comment]
#10, [#23](https://github.com/kleampa/not-paid/pull/23/files#r255074171), #34, and now #39.

We really should `let` others know what's happening in a more clear way (instead of having to `const`antly tell them).

**Comment by dyanakiev** [comment]
ie8 wont work

**Comment by etienne-martin** [comment]
Needs more jQuery.

**Pull request closed without merging**
