### PR TITLE
Cleaning js code

### PR DESCRIPTION
**Pull request by RubberDuck-Dev**
- Changing js variable names to camelCase.
- Changing variables names to be clearer.
- Removing extraneous code (calculation for opacity, converting Date to Date)
- Updating README to be clearer. Opacity starts at 100% and decreases, not increases over time.

### CODE REVIEW

**Comment by rafaeelaudibert** [comment]
Wouldn't it be clearer if the variables had the same name on README and on the JS code?

**Comment by alectrocute** [comment]
I’m going to be that annoying dude and say that I reject some of this PR.

@fl0at-on does not deserve the “modified by” line as these changes are clearly lifted from the following reddit comment without any attribution:

https://www.reddit.com/r/webdev/comments/anc72t/comment/eftnp4j?st=JRSKY7S5&sh=54e73a3f

If you want to do a PR with a few more changes that derive from your actual brain, then I have no problem with a “modified by” tag.

**Comment by RubberDuck-Dev** [comment]
As long as main PR is accepted, fine. I'd like to clarify that I didn't intend to mirror that submitter's suggestions (all of these updates are fairly common js conventions items), and that I did further than what they mention (cleaned up new Date(), used the ES6 let/const syntax, made the variable names more meaningful, edited the readme to be clearer about how opacity is handled).

Credit that other guy.

**Comment by RubberDuck-Dev** [comment]
> Wouldn't it be clearer if the variables had the same name on README and on the JS code?

Agreed. I went back and forth on the variable naming conventions. Should have caught that for the README. Updated + new attribution.

**Comment by alectrocute** [comment]
@fl0at-on No worries, thanks for clearing that up. I’ve had a rough day and my text reflected that; my apologies.

**Comment by RubberDuck-Dev** [comment]
No problemo. I appreciate you calling out something dubious - this is my first PR!

**Review by thatfiredev — APPROVED** [review]

**Comment by imlinus** [comment]
You still did the work! Good on ya mate <3

**Comment by bsoyka** [comment]
See #10 for discussion on ES6 features.

**Pull request closed without merging**
