### PR TITLE
Anti debug hook.

### PR DESCRIPTION
**Pull request by fido-node**

### CODE REVIEW

**Comment by brhx** [comment]
This PR contains a `while (true) {}` loop that will cause the CPU to spin-lock and the page will be less responsive (regardless of whether the deadline has passed or not). Performance won't matter much _after_ the deadline has exceeded, so maybe use this debug hook technique only _after_ the deadline has passed?

**Comment by fido-node** [comment]
Nice idea. Will fix ASAP.

**Comment by brhx** [comment]
Also just to explain this PR on the behalf of @michey, the anti-debug hook works like this:

> If you played a bit with a debugger and the x86 family probably you know about the 0xCC instruction. In JavaScript we have an analog instruction called debugger. Placing a debugger; sentence inside your code will produce a stop in the execution of your script when the debugger hit that instruction. 

> The tools used to debug JavaScript (for example DevTools) has the capacity of block the script execution at an arbitrary point in order to help us to understand what is happening. This is done with “breakpoints”. Using breakpoints when you are debugging helps you to see what happened, what is happening and will happen next, so they are one of the most fundamentals basis of debugging.

> If you execute this code with your DevTools opened, a prompt asking you to resume the execution will be shown. Until you press “Continue” the script will be blocked at that point. And here comes the next (pretty stupid) trick seen in comercial products: just put a infinte loop of debugger;. Some browsers prevents this situation, others not. But the concept inside this is just to annoy the guy debugging your code. The loop will flood you with a torrent of windows asking to resume the execution, so we can’t start to work reversing the script until this is fixed.

```javascript
setTimeout(function() {while (true) {eval("debugger")}});
```

https://x-c3ll.github.io/posts/javascript-antidebugging/

**Comment by TurnrDev** [comment]
Whilst I think with is an asshole technique, the true arsehole is the one not paying for a website when a payment was agreed upon. Love this.

**Comment by shubanker** [comment]
**_Its a bad Idea_**, it would give away location of code to the debugging guy easily, I tried it with `minified` version of the code and got the code location by backtracking to just one stack.

stack
At-least without this it would take some time to debug and find the location of code.

**Pull request closed without merging**
