### PR TITLE
modify code using function and use jquery syntax

### PR DESCRIPTION
**Pull request by muaz234**
hi, this is a helpful repository

to support hacktoberfest, i tried to improve your code by using jquery syntax. later i might publish this as a npm package that could fit many more projects.

please consider my PR and any comment are much appreciated.

### CODE REVIEW

**Comment by pau1phi11ips** [comment]
Interested to hear why you think making jQuery a requirement for this code makes it better @muaz234?

**Comment by muaz234** [comment]
just minimize the js syntax to improve code readibility

**Comment by AlbertoSinigaglia** [comment]
`minimize the js syntax` and importing a whole library?...

**Comment by sonrohan** [comment]
No.

**Comment by ahsan-a** [comment]
is this some kind of sick joke

**Comment by NewEXE** [comment]
Good for training, but not for production

**Comment by Sashank999** [comment]
If a website already uses jQuery in its production, I see no problem why this would add any complexity.

**Comment by cloudmaker97** [comment]
> If a website already uses jQuery in its production, I see no problem why this would add any complexity.

mind that not every website uses jQuery, in example most of my sites are jQuery-less. And i think that i'm not the only one who thinks this way. So i dont need a libary wich takes so much file size (in networking) for using just 1-2 functions.   

> Good for training, but not for production

not even for training. learn it the right way and you dont need such mess in your code base.

**Pull request closed without merging**
