### PR TITLE
Add a logo

### PR DESCRIPTION
**Pull request by brhx**
Had an idea for a logo, thought it was cool lol

screenshot 2019-02-07 at 18 17 40

### CODE REVIEW

**Comment by developerium** [comment]
idea: change ! to a fire icon

**Review by overlineink — APPROVED** [review]
Perfect! 👌

**Comment by overlineink** [comment]
@developerium I think this way it is more explicit, a fire icon would look just like my code 👉 full of variables declared implicitly.

**Comment by brhx** [comment]
@overlineink pollute that global namespace like it's the planet earth boi 🔥🔥

**Comment by bsoyka** [comment]
Here’s two, one with the original exclamation mark, and one with a fire emoji.
fd091056-4a3e-453e-8ee9-3e2bdd00ac66
77508725-de3a-4ad9-9478-8af276ee9b85

**Pull request closed without merging**
