### PR TITLE
Modifiy script to  es6 features

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
I added some es6 features to the script.
I used `const` and `let` to declare the variables and used `arrow function`

### CODE REVIEW

**Comment by cuchi** [comment]
This is nice. But I think the author's intention was to maintain the code compatible with old browsers without using stuff like babel, keeping it simple.

**Comment by jimfilippou** [comment]
Out of scope PR, there is neither ES6 build pipeline for this project nor npm scripts

**Comment by BolajiAyodeji** [comment]
> This is nice. But I think the author's intention was to maintain the code compatible with old browsers without using stuff like babel, keeping it simple.

Yes, I figured!
Thank you @cuchi

**Comment by BolajiAyodeji** [comment]
> Out of scope PR, there is neither ES6 build pipeline for this project nor npm scripts

Yes, I figured!
Thank you @jimfilippou

**Pull request closed without merging**
