### PR TITLE
Use document.body

### PR DESCRIPTION
**Pull request by maniator**

### CODE REVIEW

**Comment by sam3d** [comment]
Closey close...

**Review by Sqaaakoi — APPROVED** [review]

**Comment by Sqaaakoi** [comment]
I approve but PRs won't be accepted

**Comment by GiacomoLaw** [comment]
Out of interest, why? :)

**Comment by brhx** [comment]
@GiacomoLaw It's the decision of the maintainer, @kleampa. Also, he hasn't specified why and I don't think he will.

https://github.com/kleampa/not-paid/blob/ddfd07e118e0b642676b0180a0b71daf7357eea1/README.md#L26

**Comment by GiacomoLaw** [comment]
Okay, just found it odd! 😄

**Pull request closed without merging**
