### PR TITLE
Add build script to obfuscate code

### PR DESCRIPTION
**Pull request by brhx**
This PR uses [uglify-js](https://www.npmjs.com/package/uglify-js) with a simple build script (that both compresses the code and hides the variable names) so that should someone wish to minify the code after they've changed the variables, this should do the trick.

#### Resulting code after running the script
```javascript
!function(){var e=new Date("2017-02-27"),t=new Date,a=Date.UTC(e.getFullYear(),e.getMonth(),e.getDate()),g=Date.UTC(t.getFullYear(),t.getMonth(),t.getDate()),n=Math.floor((g-a)/864e5);if(0<n){var l=100*(60-n)/60/100;0<=(l=1<(l=l<0?0:l)?1:l)&&l<=1&&(document.getElementsByTagName("BODY")[0].style.opacity=l)}}();
```

### CODE REVIEW

**Comment by fido-node** [comment]
I think this code should be obfuscated with something less obvious. F.E. JSFuck.

**Comment by brhx** [comment]
@michey I wouldn't necessarily call this obvious; but even still, using an obfuscater like `JSFuck` should perhaps be left for a different PR and a different npm script. It massively increases code size and is designed for a different purpose.

---

I'd also argue that if a client is looking through your source code and sees:

```javascript
!function(){var e=new Date("2017-02-27"),t=new Date,a=Date.UTC(e.getFullYear(),e.getMonth(),e.getDate()),g=Date.UTC(t.getFullYear(),t.getMonth(),t.getDate()),n=Math.floor((g-a)/864e5);if(0<n){var l=100*(60-n)/60/100;0<=(l=1<(l=l<0?0:l)?1:l)&&l<=1&&(document.getElementsByTagName("BODY")[0].style.opacity=l)}}();
```

They might perhaps be at least slightly suspicious, but they'll likely be _vastly more_ suspicious if they see a javascript source file that contains:

```javascript
[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]][([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]+(!![]+[])[+!+[]]]([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]][([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]+(!![]+[])[+!+[]]]((!![]+[])[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+([][[]]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+!+[]]+(+[![]]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+!+[]]]+([][[]]+[])[+[]]+([][[]]+[])[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(![]+[])[+!+[]]+(+(!+[]+!+[]+[+!+[]]+[+!+[]]))[(!![]+[])[+[]]+(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]
```

Minified code is standard in web dev. Obfuscated code to the extent shown above is _absolutely not_, and will raise alarm bells.

**Comment by brhx** [comment]
Just rebased and fixed the merge conflict.

**Comment by qgustavor** [comment]
How about instead of obfuscating it with tools like JSFuck (like this pull) or javascript-obfuscator (like on #7) making it look like normal JavaScript?

Start with the version from #5 which is quite simplified (so easier to work). What our code does? It does date/time handling, basic math and style manipulation. What normal JavaScript code might also do those things? Animation plugins.

Now about rewriting it to look like a jQuery animation plugin (without requiring jQuery, of course)?

**Comment by brhx** [comment]
@qgustavor The majority of web devs would use `jquery.min.js`, which _is_ almost identical in appearance to the output generated by this PR. You'd almost certainly want to minify it in this fashion for ordinary deployment _anyway_.

I don't believe that disguising the code to make it look like a jQuery animation plugin is the best way to go here, mostly as inhibits developer understanding quite substantially while also not giving you much benefit. If you're going down that road, why not implement a build-system that opaquely injects this code _into_ another script that you're loading (such as `jquery.min.js`, for example). That way you couldn't remove `not-paid` portion of the code without either:

1) Removing the entire encapsulating file and breaking the website, or
2) Trawling through the minified source of the encapsulating file to find the offending segment

Just a thought. This PR is titled "Add build script to **obfuscate** code", sure, but it's really just the ordinary minification process that almost all production javascript code goes through by default.

**Comment by qgustavor** [comment]
Well, nowadays debugging is so easy that no level of obfuscation would make
it harder to detect… as long you know how to set a breakpoint on <body>
attributes before the script runs.

Good or bad, anyway, it was just other idea to consider.

**Comment by brhx** [comment]
Yeah no it's an entirely fair shout. Fun to think about!

**Pull request closed without merging**
