### PR TITLE
Remove line jumps + Add semicolon after function call

### PR DESCRIPTION
**Pull request by quantumsheep**
Just formatting the line jumps and adding a semicolon after anonymous function call

### CODE REVIEW

**Review by brhx — APPROVED** [review]
Nice catch!

I am growing increasingly pessimistic that @kleampa will ever look at these PR's, but we'll see how we go.

**Comment by bsoyka** [comment]
> I am growing increasingly pessimistic that @kleampa will ever look at these PR's

😂 Same here, I hate inactive repo owners, especially when their repo is _**featured on GitHub Explore**_!

**Review by bsoyka — APPROVED** [review]

**Comment by bsoyka** [comment]
@sam3d I just sent them an email in Romanian using Google Translate asking them to look through PRs or add a collaborator.  We’ll see how it goes.

**Comment by brhx** [comment]
I think "hate" is perhaps a bit much lol. It _can_ be frustrating but there are a huge number of reasons why @kleampa wouldn't be able to look at these PR's. A simple "no PR's or issues will be accepted for this project" would be nice (if that's their viewpoint), but they don't owe us anything.

**Comment by kleampa** [comment]
I see every message but as you can realize this "script" was created as a joke and I have no interest in make it "look cool" or adding new features.

**Comment by brhx** [comment]
@bsoyka Well, I think that answers that question pretty conclusively.

https://github.com/kleampa/not-paid/blob/ddfd07e118e0b642676b0180a0b71daf7357eea1/README.md#L26

@kleampa I'm sorry for all of the notifications you must have received over the last few days. May I recommend using http://nopullrequests.com to disable PR's as well? It automatically closes any pull requests that come in considering that [isn't a feature that GitHub has yet](https://github.com/dear-github/dear-github/issues/84).

May I also recommend creating a [pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) that lets users know that it will be closed instantly? I fully understand not wanting to field issues and PR's from users, but you have a very popular open source project and it would be courteous to make sure they're as informed as possible.

**Comment by quantumsheep** [comment]
@sam3d That's so sad, this project was cool and just needed some additions 😢

**Pull request closed without merging**
