### PR TITLE
Replace other platform text links with image links

### PR DESCRIPTION
**Pull request by theapache64**

### CODE REVIEW

**Comment by jacobsandersen** [comment]
Literally, why?

**Comment by theapache64** [comment]
**Old**
image

**New**
image

Which one is beautiful? :laughing:

**Comment by jacobsandersen** [comment]
I really don't see why it's necessary though, but whatever your repo

**Comment by ttomovcik** [comment]
Might be looking better but I don't see the point of using them in this repo. Also, he's not acccepting any PRs so.. There's that.

**Pull request closed without merging**
